# Generated by Django 5.1.6 on 2025-03-05 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worker',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
        migrations.AddField(
            model_name='worker',
            name='helmet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worhel', to='main.helmet'),
        ),
        migrations.AddField(
            model_name='worker',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='main.tagmodel'),
        ),
    ]
