# Generated by Django 5.1.6 on 2025-02-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
