# Generated by Django 5.1.6 on 2025-02-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_worker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Unpublished'), (1, 'Published')], default=0),
        ),
    ]
