# Generated by Django 5.1.6 on 2025-02-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_worker_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
