# Generated by Django 5.1.6 on 2025-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_helmet_worker_helmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmet',
            name='usage_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
