# Generated by Django 5.1.6 on 2025-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_helmet_usage_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Best team ever', 'verbose_name_plural': 'Best team ever'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
    ]
