# Generated by Django 5.1.6 on 2025-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_worker_photo_alter_worker_content_alter_worker_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y-%m-%d', verbose_name='Photo'),
        ),
    ]
