# Generated by Django 5.1.6 on 2025-02-27 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_worker_description_alter_worker_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='photos_other/%Y/%m/%d'),
        ),
    ]
