# Generated by Django 5.1.6 on 2025-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_worker_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='tags', to='main.tagmodel'),
        ),
    ]
