# Generated by Django 5.1.6 on 2025-02-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_worker_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
